### ISSUE TITLE
使用grid布局实现经典两栏布局

### ISSUE THREAD

**Issue by da34** [da34/interview#48]
```css
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .wrap {
            display: grid;
            grid: 100px 1fr 30px / 200px 1fr;
        }
        header {
            background: red;
            grid-area: 1 /3/ 2/ 1;
        }
        aside {
            background: blue;
            grid-area: 2 /2/ 3/ 1;
        }
        main {
            background: pink;
            grid-area: 2 /3/ 3/ 2;
        }
        footer {
            background: #000;
            color: #fff;
            grid-area: 3 /3/ 4/ 1;
        }
    </style>
</head>

<body>
    <div class="wrap">
        <header>我是头部</header>
        <aside>我是左侧</aside>
        <main>我是主体内容</main>
        <footer>我是底部</footer>
    </div>
</body>

</html>
```
> 题目来自饥人谷
